--! Previous: sha1:39031990bc305db92605c7271292cfb7067697fd
--! Hash: sha1:01d1c196be25caceb3e4f4c3d2b65dd3fa2865d2

-- Enter migration here
drop function if exists visitor_metrics;
create table if not exists visitor_metrics (
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id int references projects(id),
  start TIMESTAMPTZ NOT NULL,
  last_updated TIMESTAMPTZ NOT NULL,
  interval interval not null,
  top_referrers jsonb,
  top_operating_systems jsonb,
  top_browsers jsonb,
  top_device_types jsonb,
  top_countries jsonb
);

create index on visitor_metrics (project_id, start, interval);
alter table visitor_metrics enable row level security;
drop policy if exists select_visitor_metrics on visitor_metrics;
create policy select_visitor_metrics on visitor_metrics for select using (session_is_superuser() or (project_id is not null and session_is_admin(project_id)));


create or replace function visitor_metrics(period activity_stats_period)
  returns setof visitor_metrics
  language sql
  stable
  security definer
  as $$
    select * from visitor_metrics where session_is_superuser() and project_id is null and
    interval = (
      case period
        when '24hrs' then '1 day'::interval
        when '7-days' then '7 days'::interval
        when '30-days' then '30 days'::interval
        else '1 day'::interval
      end
    ) order by start desc limit 1;
  $$;

grant execute on function visitor_metrics to seasketch_user;

comment on function visitor_metrics is '@simpleCollections only';
