version: "3"
services:
  db:
    container_name: "seasketch_db"
    image: underbluewaters/postgres-13-postgis-3.1
    ports:
      - "54321:5432"
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./init_dockerdb.sql:/docker-entrypoint-initdb.d/init_dockerdb.sql
    command: ["postgres", "-c", "log_statement=all"]
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
