version: "3"
services:
  db:
    container_name: "seasketch_db"
    build: .
    ports:
      - "54321:5432"
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./init_dockerdb.sql:/docker-entrypoint-initdb.d/init_dockerdb.sql
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
