--! Previous: sha1:cb794d1eab4242f730ca6106e2f602dfd7b398ea
--! Hash: sha1:4001deb4b22709eab229e397b05236fd01030c0f

-- Enter migration here
DROP SCHEMA IF EXISTS app_private CASCADE;

CREATE SCHEMA app_private;

DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE users (
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  legacy_id text UNIQUE,
  email text UNIQUE,
  sub text UNIQUE,
  accepted_privacy_policy boolean DEFAULT FALSE,
  registered_at timestamp WITH time zone DEFAULT (now() at time zone 'utc')
);

CREATE INDEX users_sub ON users (sub);

GRANT SELECT (id) ON users TO anon;

COMMENT ON COLUMN users.legacy_id IS 'Legacy SeaSketch MongoDB ObjectId, if applicable';

COMMENT ON COLUMN users.sub IS 'From auth provider jwt token (Auth0)';
