--! Previous: sha1:cb794d1eab4242f730ca6106e2f602dfd7b398ea
--! Hash: sha1:56f8128b35bc87c7a8d6dcb7ae33556081b44254

DROP SCHEMA IF EXISTS app_private CASCADE;

CREATE SCHEMA app_private;

DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE users (
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  legacy_id text UNIQUE,
  email text UNIQUE,
  sub text UNIQUE,
  accepted_privacy_policy boolean DEFAULT FALSE,
  registered_at timestamp WITH time zone DEFAULT (now() at time zone 'utc')
);

CREATE INDEX users_sub ON users (sub);

GRANT SELECT (id) ON users TO anon;

COMMENT ON COLUMN users.legacy_id IS 'Legacy SeaSketch MongoDB ObjectId, if applicable';

COMMENT ON COLUMN users.sub IS 'From auth provider jwt token (Auth0)';

DROP TABLE IF EXISTS user_profiles CASCADE;

DROP EXTENSION IF EXISTS citext CASCADE;

CREATE EXTENSION citext;

CREATE DOMAIN email AS citext CHECK (value ~ '^[a-zA-Z0-9.!#$%&''*+/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$');

CREATE TABLE user_profiles (
  -- id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL UNIQUE REFERENCES users (id) ON DELETE CASCADE,
  fullname text,
  nickname text,
  picture text CHECK (picture::text ~* 'https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{2,255}\.[a-z]{2,9}\y([-a-zA-Z0-9@:%_\+.~#?&//=]*)$'::text),
  email email,
  affiliations text,
  bio text
);

GRANT SELECT ON user_profiles TO anon;

CREATE INDEX ON "public"."user_profiles" ("user_id");

COMMENT ON CONSTRAINT "user_profiles_user_id_fkey" ON user_profiles IS E'@omit many';
