--! Previous: sha1:56f8128b35bc87c7a8d6dcb7ae33556081b44254
--! Hash: sha1:93e8475ca1be3c6a051674eb1a31cfe6322c0f57

-- Enter migration here
DROP TABLE IF EXISTS project_participants CASCADE;

CREATE TABLE project_participants (
  user_id integer NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  project_id integer NOT NULL REFERENCES projects (id) ON DELETE CASCADE,
  is_admin boolean DEFAULT FALSE,
  PRIMARY KEY (user_id, project_id)
);

CREATE INDEX project_participants_project_id ON project_participants (project_id);

CREATE INDEX project_participants_user_id ON project_participants (user_id);

CREATE INDEX project_participants_is_admin ON project_participants (is_admin);

GRANT SELECT ON project_participants TO seasketch_user;

COMMENT ON TABLE project_participants IS E'@name participants';

DROP TABLE IF EXISTS project_groups CASCADE;

CREATE TABLE project_groups (
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id integer NOT NULL REFERENCES projects (id) ON DELETE CASCADE,
  name text CONSTRAINT namechk CHECK (char_length(name) <= 32)
);

CREATE INDEX project_groups_project_id ON project_groups (project_id);

GRANT SELECT ON project_groups TO seasketch_user;

COMMENT ON TABLE project_groups IS E'@name groups';

DROP TABLE IF EXISTS project_group_members CASCADE;

CREATE TABLE project_group_members (
  group_id integer NOT NULL REFERENCES project_groups (id) ON DELETE CASCADE,
  user_id integer NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  PRIMARY KEY (group_id, user_id)
);

CREATE INDEX project_group_members_group_id ON project_group_members (group_id);

CREATE INDEX project_group_members_user_id ON project_group_members (user_id);

GRANT SELECT ON project_group_members TO seasketch_user;

COMMENT ON TABLE project_group_members IS E'@name group_members\n';
