--! Previous: sha1:4001deb4b22709eab229e397b05236fd01030c0f
--! Hash: sha1:a69b8c6b670c338c945ab1a030ec40bdcb65ef40

DROP TABLE IF EXISTS user_profiles CASCADE;

DROP EXTENSION IF EXISTS citext CASCADE;

CREATE EXTENSION citext;

CREATE DOMAIN email AS citext CHECK (value ~ '^[a-zA-Z0-9.!#$%&''*+/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$');

CREATE TABLE user_profiles (
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer UNIQUE NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  fullname text,
  nickname text,
  picture text CHECK (picture::text ~* 'https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{2,255}\.[a-z]{2,9}\y([-a-zA-Z0-9@:%_\+.~#?&//=]*)$'::text),
  email email,
  affiliations text,
  bio text
);

GRANT SELECT ON user_profiles TO anon;
