--! Previous: sha1:e72e8d4d74c4bf4a81f37ba0fa4cde6833541002
--! Hash: sha1:cb794d1eab4242f730ca6106e2f602dfd7b398ea

-- DROP all the things so that current.sql can be re-run idempotently
DROP FUNCTION IF EXISTS projects_url (projects projects);

DROP FUNCTION IF EXISTS projects_default_locale (projects);

DROP POLICY IF EXISTS update_projects_superuser ON projects;

DROP POLICY IF EXISTS select_projects_superuser ON projects;

DROP TABLE IF EXISTS projects;

DROP TYPE IF EXISTS project_access_control_setting;

-- Done dropping things
ALTER DEFAULT PRIVILEGES REVOKE EXECUTE ON functions FROM PUBLIC;

CREATE TYPE project_access_control_setting AS enum (
  'admins_only',
  'invite_only',
  'public'
);

CREATE TABLE projects (
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  description text,
  legacy_id text UNIQUE,
  slug varchar(16) NOT NULL UNIQUE,
  access_control project_access_control_setting DEFAULT 'admins_only',
  is_listed boolean DEFAULT TRUE,
  logo_url text CHECK (logo_url::text ~* 'https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{2,255}\.[a-z]{2,9}\y([-a-zA-Z0-9@:%_\+.~#?&//=]*)$'::text),
  logo_link text CHECK (logo_link::text ~* 'https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{2,255}\.[a-z]{2,9}\y([-a-zA-Z0-9@:%_\+.~#?&//=]*)$'::text),
  is_featured boolean DEFAULT FALSE,
  is_deleted boolean DEFAULT FALSE,
  deleted_at timestamp WITH time zone
);

CREATE INDEX project_slugs ON projects (slug);

CREATE INDEX project_ids ON projects (id);

CREATE INDEX project_access_control ON projects (access_control);

CREATE INDEX project_is_deleted ON projects (is_deleted);

CREATE INDEX project_is_featured ON projects (is_featured);

CREATE FUNCTION projects_url (p projects)
  RETURNS text
  AS $$
  SELECT
    'https://seasketch.org/' || p.slug || '/'
$$
LANGUAGE SQL
STABLE;

-- grants to anon apply to everyone
GRANT EXECUTE ON FUNCTION projects_url (projects) TO anon;

GRANT SELECT ON projects TO anon;

COMMENT ON TABLE projects IS E'@omit delete';

COMMENT ON COLUMN projects.legacy_id IS E'MongoDB ObjectId from previous database';

COMMENT ON COLUMN projects.legacy_id IS E'@omit';

COMMENT ON COLUMN projects.logo_url IS E'URL referencing an image that will be used to represent the project. Will be displayed at 48x48 pixels';

COMMENT ON COLUMN projects.logo_link IS E'If a logoUrl is provided, it will link to this url in a new window if provided.';

COMMENT ON COLUMN projects.is_featured IS E'Featured projects may be given prominent placement on the homepage.';

COMMENT ON COLUMN projects.is_deleted IS E'@omit';

COMMENT ON COLUMN projects.deleted_at IS E'@omit';

COMMENT ON COLUMN projects.slug IS E'Will resolve to https://seasketch.org/{slug}/ and cannot be changed';
