version: '3'
services:
  db:
    image: postgres:12-alpine
    ports:
    - "54320:5432"
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./init_dockerdb.sql:/docker-entrypoint-initdb.d/init_dockerdb.sql