name: Create Release Tags
on:
  pull_request:
    types: [closed]
    # branches:
    #   - master
jobs:
  tag_release:
    runs-on: ubuntu-latest
    if: contains( github.event.pull_request.labels.*.name, 'release')
    # && github.event.pull_request.merged == true
    name: Create a release tag
    steps:
      - name: Get tag name
        id: get_tag
        run: |
          echo ${{ github.event.pull_request.title }} | grep -Eo '[[:digit:]]+.[[:digit:]]+.[[:digit:]]$'
          echo "::set-output name=tag::`echo ${{ github.event.pull_request.title }} | grep -Eo '[[:digit:]]+.[[:digit:]]+.[[:digit:]]$'`"
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{steps.get_tag.outputs.tag}}
