name: Release PR Manager
on: push
jobs:
  create_or_update_pr:
    runs-on: ubuntu-latest
    name: Create or update release pull-request
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-lerna-version-node-modules
        with:
          path: |
            node_modules
            */*/node_modules
            ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install lerna
        run: |
          npm install
      - name: get changed packages
        run: |
          npx lerna changed --all --json > changed.json
      - name: get previous tag
        id: prev_tag
        run: |
          echo "::set-output name=tag::`npx git-semver-tags --lerna | head -n 1`"
      - name: detect migrations
        run: |
          git diff --name-only ${{ steps.prev_tag.outputs.tag }} -- packages/api/migrations/committed
          git diff --name-only ${{ steps.prev_tag.outputs.tag }} -- packages/api/migrations/committed > migrations.txt
          [ -s migrations.txt ] || echo "::set-output name=has_migrations::yes"
      - name: run lerna version
        run: |
          git config --global user.email "releases@seasketch.org"
          git config --global user.name "Release Manager"
          git checkout --
          npx lerna version --conventional-commits --no-push --yes
      - name: get new package versions
        run: |
          npx lerna list -a --json > list.json
      - name: Get highest version
        id: release_version
        run: |
          npm install compare-versions
          echo "::set-output name=version::`node -e "var compareVersions = require('compare-versions'); console.log(require('./list.json').filter((p) => p.name === 'client' || p.name === '@seasketch/api').map((p) => p.version).sort(compareVersions).reverse()[0])"`"
          git checkout -- package-lock.json package.json
      - name: Generate changelogs
        run: |
          npx standard-changelog -i .changelog.md
          echo "# v${{steps.release_version.outputs.version}}\n\n" > short_changelog.md
          tail -n +1 .changelog.md >> short_changelog.md
          cat short_changelog.md | cat - CHANGELOG.md > temp && mv temp CHANGELOG.md
          git add CHANGELOG.md
          git commit -m 'Update Changelog for v${{steps.release_version.outputs.version}}'
      - name: Create pull request message
        id: pull_request_message
        run: |
          node ./createReleaseSummary.js
      - name: Create Pull Request
        id: pr
        uses: peter-evans/create-pull-request@v3
        with:
          # base: master
          # branch: feature-ci-cd-actions
          author: Release Manager <releases@seasketch.org>
          title: Release ${{steps.release_version.outputs.version}}
          body: |
            ${{ steps.pull_request_message.outputs.message }}
      # Do this within deployment pipeline
      # - name: Bump version and push tag
      #   id: tag_version
      #   uses: mathieudutour/github-tag-action@v5.6
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     custom_tag: ${{steps.release_version.outputs.version}}
