name: CI/CD
on: push
jobs:
  test-server:
    name: Test GraphQL API Server
    runs-on: ubuntu-latest
    services:
      postgres:
        image: underbluewaters/seasketch_db_base
        ports:
          - "5432:5432"
        env:
          POSTGRES_PASSWORD: password
      redis:
        image: "redis:alpine"
        ports:
          - "6379:6379"
    steps:
      - uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: |
            node_modules
            */*/node_modules
            ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Install lerna
        run: |
          npm install
      - name: Install dependencies
        run: |
          lerna bootstrap --scope=@seasketch/api
      - name: Init docker db
        working-directory: ./packages/api
        env:
          TEST_DB: postgres://postgres:password@localhost:5432/
        run: |
          node tests/init_dockerdb.js
      - name: Run Tests
        working-directory: ./packages/api
        run: |
          npx jest --ci --reporters=default --reporters=jest-junit
        env:
          TEST_DB: postgres://postgres:password@localhost:5432/
          SES_EMAIL_SOURCE: do-not-reply@seasketch.org
      - uses: IgnusG/jest-report-action@v2.3.1
        if: always()
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: ./packages/api
          check-name: API Test Output
          run-name: api
  test-client:
    name: Test React Client
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: |
            node_modules
            */*/node_modules
            ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Install lerna
        run: |
          npm install
      - name: Install dependencies
        run: |
          lerna bootstrap --scope=client --scope=mapbox-gl-esri-feature-layers
      - name: Test client
        working-directory: ./packages/client
        env:
          SKIP_PREFLIGHT_CHECK: true
        run: |
          npm run test
  build-client:
    name: Build React Client
    runs-on: ubuntu-latest
    needs: test-client
    steps:
      - uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: |
            node_modules
            */*/node_modules
            ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Install lerna
        run: |
          npm install
      - name: Install dependencies
        run: |
          lerna bootstrap --scope=client --scope=mapbox-gl-esri-feature-layers
      - name: Build client
        working-directory: ./packages/client
        env:
          SKIP_PREFLIGHT_CHECK: true
        run: |
          npm run build
  run-migrations:
    name: Run Database Migrations
    runs-on: ubuntu-latest
    needs: test-server
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.TEST_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.TEST_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: Run migrations using ecs exec
        run: |
          aws ecs execute-command --cluster ${{secrets.MAINTENANCE_STACK}} --task ${{secrets.MAINTENANCE_TASK}} --container Default --command "/bin/sh -l /home/migrate.sh" --interactive
